### ISSUE TITLE
Upload command (put) in mediafire-shell causes segfault

### ISSUE THREAD

**Issue by bucaneer** [MediaFire/mediafire-fuse#5]
Whenever I attempt to upload a file through `mediafire-shell`, it segfaults. Backtrace of generated core file:
```
(gdb) bt
#0  0x00007f191889c7d4 in free () from /usr/lib/libc.so.6
#1  0x00000000004105aa in mfconn_api_upload_simple ()
#2  0x0000000000405b17 in mfshell_cmd_put ()
#3  0x0000000000404604 in mfshell_exec ()
#4  0x0000000000404786 in mfshell_exec_shell_command ()
#5  0x00000000004049f1 in mfshell_run ()
#6  0x0000000000404410 in main ()
```

Running up-to-date Arch Linux, glibc version 2.20.

**Comment by josch** [comment]
thanks, this should be fixed now

**Comment by bucaneer** [comment]
Confirmed fix. Thank you.
